version: "3"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: on-failure

  scylla:
    image: scylladb/scylla:latest
    container_name: scylla-node
    ports:
      - "9042:9042"
      - "9180:9180"
    volumes:
      - scylla-data:/var/lib/scylla
      - scylla-logs:/var/log/scylla
    command: --smp 1 --memory 1G --overprovisioned 1
    networks:
      - scylla-net

volumes:
  scylla-data:
  scylla-logs:

networks:
  scylla-net:
    driver: bridge
